kcl-lang/lib

- install.go
+ feat: add more scripts uninstall
+ chore: upgrade cdylibs
```release-note
None
```
> Upgrade kclvm cdylibs

- kclvm_cli_shared_lib_windows_amd64.go
- kclvm_cli_shared_lib_windows_arm64.go
- lib/dummy.go
- lib/windows-amd64/dummy.go
- lib/windows-arm64/dummy.go
feat: add windows libs to prevent errors. todo: more windows bin and lib embed
```release-note
None
```
> feat: add windows libs to prevent errors

- scripts/kcl
- scripts/kcl-doc
- scripts/kcl-fmt
- scripts/kcl-lint
- scripts/kcl-plugin
- scripts/kcl-vet
> feat: add -U flag in python3 pip commands.

- install_lib_windows.go
chore: upgrade all libs to 0.4.4
```release-note
None
```
> chore: upgrade all libs to 0.4.4

- install.go
refactor: kclvm lib install order.
```release-note
None
```
> refactor: kclvm lib install order.

- install.go
chore: bump kcl version to v0.5.1
> chore: bump kcl version to v0.5.1

- install.go
feat: add arch and os in the version string
> feat: add arch and os in the version string

- .github/workflows/ci.yaml
- .gitignore
- java/Makefile
- java/src/main/java/com/kcl/api/API.java
- java/src/main/java/com/kcl/api/Service.java
- java/src/main/java/com/kcl/api/Spec.java
- java/src/main/java/com/kcl/ast/SchemaAttr.java
- java/src/main/java/com/kcl/loader/SymbolKind.java
- java/src/main/java/com/kcl/loader/SymbolRef.java
- java/src/main/java/com/kcl/util/JsonUtil.java
- java/src/test/java/com/kcl/LoadPackageTest.java
- java/src/test_data/schema.k
- python/kcl_py_lib/api/service.py
- python/scripts/requirements.txt
- python/tests/parse_test.py
- python/tests/test_data/schema.k
- spec/gpyrpc/spec.proto
+ feat: impl KCL Java symbol API
+ java/src/main/java/com/kcl/api/API.java
+ java/src/main/java/com/kcl/api/Service.java
+ java/src/main/java/com/kcl/loader/SymbolKind.java
+ java/src/main/java/com/kcl/util/JsonUtil.java
+ spec/gpyrpc/spec.proto
> feat: impl KCL Java symbol API

- java/src/main/java/com/kcl/ast/AnyType.java
- java/src/main/java/com/kcl/ast/BasicType.java
- java/src/main/java/com/kcl/ast/BinaryExpr.java
- java/src/main/java/com/kcl/ast/BoolLiteralType.java
- java/src/main/java/com/kcl/ast/DictType.java
- java/src/main/java/com/kcl/ast/Expr.java
- java/src/main/java/com/kcl/ast/FloatLiteralType.java
- java/src/main/java/com/kcl/ast/FunctionType.java
- java/src/main/java/com/kcl/ast/Identifier.java
- java/src/main/java/com/kcl/ast/IdentifierExpr.java
- java/src/main/java/com/kcl/ast/ImportStmt.java
- java/src/main/java/com/kcl/ast/IntLiteralType.java
- java/src/main/java/com/kcl/ast/Keyword.java
- java/src/main/java/com/kcl/ast/ListType.java
- java/src/main/java/com/kcl/ast/LiteralType.java
- java/src/main/java/com/kcl/ast/LiteralTypeValue.java
- java/src/main/java/com/kcl/ast/NameConstantLit.java
- java/src/main/java/com/kcl/ast/NamedType.java
- java/src/main/java/com/kcl/ast/NumberLit.java
- java/src/main/java/com/kcl/ast/SchemaAttr.java
- java/src/main/java/com/kcl/ast/SchemaConfig.java
- java/src/main/java/com/kcl/ast/StrLiteralType.java
- java/src/main/java/com/kcl/ast/StringLit.java
- java/src/main/java/com/kcl/ast/UnificationStmt.java
- java/src/main/java/com/kcl/ast/UnionType.java
- java/src/test/java/com/kcl/LoadPackageTest.java
- java/src/test_data/schema.k
+ refactor: enhance kcl ast in java
> refactor: enhance kcl ast in java

- java/src/main/java/com/kcl/api/Spec.java
- java/src/main/java/com/kcl/ast/Module.java
- java/src/main/java/com/kcl/ast/Node.java
- java/src/main/java/com/kcl/ast/NodeRef.java
- java/src/main/java/com/kcl/ast/Program.java
- java/src/main/java/com/kcl/loader/ScopeKind.java
- java/src/main/java/com/kcl/loader/ScopeRef.java
- java/src/main/java/com/kcl/util/JsonUtil.java
- java/src/main/java/com/kcl/util/SematicUtil.java
- java/src/test/java/com/kcl/LoadPackageTest.java
- spec/gpyrpc/spec.proto
+ feat: semantic API for Java SDK
+ spec/gpyrpc/spec.proto
+ java/src/main/java/com/kcl/api/Spec.java
+ java/src/main/java/com/kcl/ast/Module.java
+ java/src/main/java/com/kcl/ast/Node.java
+ java/src/main/java/com/kcl/util/JsonUtil.java
+ java/src/test/java/com/kcl/LoadPackageTest.java
> feat: semantic scope API for Java SDK

- java/src/main/java/com/kcl/api/Spec.java
- java/src/main/java/com/kcl/util/SematicUtil.java
- java/src/test/java/com/kcl/LoadPackageTest.java
- spec/gpyrpc/spec.proto
+ feat: add symbol to node and type symbol APIs. See java/src/test/java/com/kcl/LoadPackageTest.java for more examples
> Note: the `ty` filed of `Symbol` is changed to `KclType` from `String`
+ java/src/main/java/com/kcl/api/Spec.java
+ java/src/main/java/com/kcl/util/SematicUtil.java
+ java/src/test/java/com/kcl/LoadPackageTest.java
> feat: add symbol to node and type symbol APIs

- .github/workflows/ci.yaml
- README.md
- java/Makefile
- java/README.md
- java/pom.xml
- java/scripts/build.py
- java/src/main/java/com/kcl/api/API.java
- java/src/main/java/com/kcl/api/Environment.java
- java/src/main/resources/META-INF/MANIFEST.MF
+ feat: support kcl java lib release for different platforms
+ .github/workflows/ci.yaml
+ README.md
+ java/Makefile
+ java/README.md
+ java/pom.xml
+ java/scripts/build.py
+ java/src/main/java/com/kcl/api/API.java
+ java/src/main/java/com/kcl/api/Environment.java
> feat: support kcl java lib release for different platforms

- .github/workflows/ci.yaml
- .github/workflows/release_python.yaml
- README.md
- java/pom.xml
- python/.gitignore
- python/Makefile
- python/kcl_lib/api/service.py
- python/kcl_lib/bootstrap/__init__.py
- python/kcl_lib/bootstrap/artifact.py
- python/scripts/requirements.txt
- python/setup.py
+ feat: add kcl python lib release
> feat: add kcl python lib release

- .github/workflows/ci.yaml
- java/Makefile
- java/pom.xml
> chore: release java in CI

- python/kcl_lib/api/service.py
> fix: kcl lib install

- Cargo.toml
- install.go
- java/pom.xml
- python/kcl_lib/api/service.py
- python/kcl_lib/bootstrap/__init__.py
- python/kcl_lib/bootstrap/artifact.py
- python/setup.py
> fix: kcl lib release folder

- java/pom.xml
> chore: remove dependency on fastjson

- .github/workflows/go-test.yaml
- .github/workflows/java-test.yaml
- .github/workflows/rust-test.yaml
+ ci: split multiple SDKs test to diffrent CI scripts
> ci: split multiple SDKs test to diffrent CI scripts

- .github/workflows/java-test.yaml
> fix: fix ci and add classifier for jar

- Cargo.toml
- install.go
- java/Cargo.toml
- java/pom.xml
- nodejs/package.json
- python/Cargo.toml
- python/setup.py
+ chore: bump kcl libs to v0.8.5
> chore: bump kcl libs to v0.8.5

- .github/workflows/java-test.yaml
> fix: update centos gcc version to 4.8.5

- java/src/main/java/com/kcl/api/Spec.java
- java/src/test/java/com/kcl/ListVariablesTest.java
- java/src/test_data/list_variables/main.k
- spec/gpyrpc/spec.proto
> feat(java): add type name for schema expr in api ListVariables

- util.go
Fix https://github.com/kcl-lang/lib/issues/73
- `util.go`
An application using KCL does not crash after installing a different version of KCL.
See https://github.com/kcl-lang/lib/issues/73
> Write library by temporary file creation to avoid in-place modification executed library

- util_unix.go
- util_windows.go
+ feat: write lib without temp renaming file on windows
> feat: write lib without temp renaming file on windows

- .github/workflows/java-test.yaml
- java/pom.xml
> fix: add timestamp for kcl java jar

- src/lib.rs
> fix: fix protobuf error

- python/src/lib.rs
fix: python api calling signature
> fix: python api calling signature

- .github/workflows/java-test.yaml
> fix: fix typo

- .github/workflows/python-test.yaml
> fix: bump pkginfo version to 1.12.0

- .github/dependabot.yml
~~* update actions/download-artifact to v4.~~
~~* update actions/upload-artifact to v4.~~
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Let's get rid of the pain of expired action as soon as possible.
> chore: add dependabot to auto update github workflow files.

- .github/workflows/python-test.yaml
> fix: fix python release github action

- .github/workflows/dotnet-test.yaml
> fix: fix dotnet release github action
